### ISSUE TITLE
About dialog

### ISSUE THREAD

**Issue by zagortenay333** [pixunil/cinnamon-applet-system-monitor#12]
Mind throwing some info into the about dialog?

**Comment by pixunil** [comment]
Which content do you have in mind?
A [quick overview](https://github.com/pixunil/cinnamon-applet-system-monitor#modules), or a more extended description?

**Comment by zagortenay333** [comment]
Dunno. Personally I like having  the link to the github page; otherwise, I need to go first to the spices site to find it.
