### ISSUE TITLE
Add padding to values

### ISSUE THREAD

**Issue by kevlogan90** [pixunil/cinnamon-applet-system-monitor#16]
Would it be possible to add a padding to the display on the panel? Currently if CPU jumps from 9% to 10% all of the applets will shift around for the extra digit, and then jump back if the CPU goes below 10% again.

**Comment by pixunil** [comment]
Sorry for he late response. Yes it world be possible, but I currently can't think of a better method than using hardcoded values which _could_ fail with some fonts or themes, I need to experiment here.

**Comment by pixunil** [comment]
Found a better method: The applet now inserts `U+2007` before the digits, so other text does not jump around.
