### ISSUE TITLE
CPU temperature is only displayed in Celsius.

### ISSUE THREAD

**Issue by tsjnachos117** [pixunil/cinnamon-applet-system-monitor#22]
I have my applet set to show me the CPU temperature in Fahrenheit. The currently applet says "51.0°F", which is the equivalent of "10.5556°C". It's currently a bit cold where I live, but not that cold! :scream:

According to another program (xfce4-sensors), my CPU is 51° Celsius, so obviously the applet is displaying my CPU temperature in Celsius, and placing a capital "F" next to it. IDK if there's some kind of Celsius > Fahrenheit conversion that isn't working, or if there's something else going on, but something just isn't quite working.

I'm currently running Cinnamon 3.4.0, but I just upgraded from 3.2.8, which also suffered from this issue.

PS: I'm the same user who filed bug #21, which has semi-recent copies of my .xsession-errors glass.log files. I can upload more recent versions of said files if needed.

**Comment by pixunil** [comment]
That was a regression when I changed the settings. So you were right, it just swaps the unit
