### ISSUE TITLE
The option to display the temp as text seems to have been removed?

### ISSUE THREAD

**Issue by ham1** [pixunil/cinnamon-applet-system-monitor#7]
I just updated to the latest code and noticed that the option to select text (i.e. a number) for the temperature display on the bar next to the other graphs was no longer there, are you able to put this back?

**Comment by pixunil** [comment]
The setting changed to a string with [placeholders](https://github.com/pixunil/cinnamon-applet-system-monitor#thermal).
Go to Settings > Thermal > Label in the panel and type in `%t0` to display the calculated thermal value or any number for a sensor.
I implemented this as it is more flexible than a ComboBox and I hope to get this a bit more easier than now, if you have any idea, it would be great.

**Comment by ham1** [comment]
Ah, I didn't read that ;) yes, I agree it's better this way.

I think, to make it obvious, if the field is blank, you could use an example similar to the html form placeholder values. e.g. http://diveintohtml5.info/forms.html and put something like "Use %t0, %t1 ... etc. to display the temp directly in the panel."

Or you could have a little help icon and it display that text when someone clicks or hovers over it?

**Comment by pixunil** [comment]
Placeholders are not possible (yet) as cinnamon-settings doesn't support it. But I look how helpful a tooltip (which is supported) could be (also for other settings)
