### ISSUE TITLE
Unicode characters

### ISSUE THREAD

**Issue by zagortenay333** [pixunil/cinnamon-applet-system-monitor#8]
Hi.

I was wondering whether you'd consider using the '°C' unicode instead of only '°' + normal letter C. The weather applet seems to be using it, and when the two applets sit next to each other there is a weird inconsistency.
See: https://github.com/mockturtl/cinnamon-weather/issues/110

Not sure which is the right method, but I figured why not be consistent.  :smile:

**Comment by pixunil** [comment]
I didn't even know that this character exists, thanks for mentioning it.

**Comment by zagortenay333** [comment]
Awesome! :smile:
