### ISSUE TITLE
Placeholders not working

### ISSUE THREAD

**Issue by dasrohr** [pixunil/cinnamon-applet-system-monitor#9]
Hey!

I'm having a problem by using the Placeholders in the panel-labels.
Every placeholder I enter, is writing "undefined" in my Panel. Even the Example "CPU: %ta" from Readme.

I still tried to restart cinnamon after change the applet-settings, but it makes no change.
Is this Feature still in Progress or is there a mistake on my side?

Greetings

**Comment by pixunil** [comment]
Yes, I heard it also from a guy in IRC, so this is already fixed in 3892a276ec527a087b8fe71e73d58269249ceefc.
It isn't released yet, as I wanted to simplify settings.
To solve the issue for you, you can run this command:
```
git clone https://github.com/pixunil/cinnamon-applet-system-monitor.git ~/.local/share/cinnamon/applets/system-monitor@pixunil
```
and restart Cinnamon.

**Comment by pixunil** [comment]
FYI: the code is now with some other improvements in release [3.6](https://github.com/pixunil/cinnamon-applet-system-monitor/releases/tag/3.6).

**Comment by dasrohr** [comment]
Thanks!
updated to Release 3.6. Everything works fine!

Nice Applet :-) realy like it!
